
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Sales extends javax.swing.JFrame {

    public Sales() {
        initComponents();
        Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pos", "root", "India_143");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCode1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQty1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCode2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQty2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCode3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQty3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCode4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQty4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtCode5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtQty5 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCode6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtQty6 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCode7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtQty7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtCode8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtQty9 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtCode9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtQty10 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtCode10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtQty11 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtCode11 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtQty12 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtCode12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtQty13 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtCode13 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtQty14 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtCode14 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtQty15 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txtCode15 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtQty16 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtQty17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        lblSubtoal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblltems = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lblItems = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtBal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtSub = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Billings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 90));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Qty", "Price", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 860, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Item Code");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeKeyReleased(evt);
            }
        });
        jPanel2.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Proname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, 30));

        txtpname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 220, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Item Code");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(txtCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Qty");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(txtQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Item Code");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Qty");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Item Code");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.add(txtCode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Qty");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.add(txtQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Item Code");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel6.add(txtCode4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Qty");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel6.add(txtQty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Item Code");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel7.add(txtCode5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Qty");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel7.add(txtQty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Item Code");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel8.add(txtCode6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Qty");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel8.add(txtQty6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Item Code");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel9.add(txtCode7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Qty");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel9.add(txtQty7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Qty");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Item Code");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel10.add(txtCode8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Price");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 30));

        txtQty9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel10.add(txtQty9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, 30));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Item Code");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel11.add(txtCode9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText("Qty");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel11.add(txtQty10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Item Code");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel12.add(txtCode10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Qty");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel12.add(txtQty11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("Item Code");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel13.add(txtCode11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("Qty");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel13.add(txtQty12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Item Code");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel14.add(txtCode12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Qty");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel14.add(txtQty13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel29.setText("Item Code");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel15.add(txtCode13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("Qty");
        jPanel15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel15.add(txtQty14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setText("Item Code");
        jPanel16.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel16.add(txtCode14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("Qty");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel16.add(txtQty15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("Item Code");
        jPanel17.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        txtCode15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel17.add(txtCode15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setText("Qty");
        jPanel17.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel17.add(txtQty16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setText("Qty");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        txtQty17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel10.add(txtQty17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 180));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setText("Price");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 30));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel38.setText("Total");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 50));

        lblSubtoal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSubtoal.setForeground(new java.awt.Color(0, 0, 153));
        lblSubtoal.setText("0.00");
        jPanel2.add(lblSubtoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 860, 160));

        lblltems.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel39.setText("Total");

        lblItems.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblItems.setForeground(new java.awt.Color(0, 0, 153));
        lblItems.setText("0");
        lblItems.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblItemsAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setText("Bill Type");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setText("Items");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel44.setText("Paid");

        txtPay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });
        txtPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayKeyPressed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel45.setText("Balance");

        txtBal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtSub.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        javax.swing.GroupLayout lblltemsLayout = new javax.swing.GroupLayout(lblltems);
        lblltems.setLayout(lblltemsLayout);
        lblltemsLayout.setHorizontalGroup(
            lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblltemsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblltemsLayout.createSequentialGroup()
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblltemsLayout.createSequentialGroup()
                        .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblltemsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblltemsLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(19, 19, 19))))
                            .addGroup(lblltemsLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblltemsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblltemsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblltemsLayout.createSequentialGroup()
                                        .addComponent(lblItems)
                                        .addGap(70, 70, 70))
                                    .addComponent(txtSub)
                                    .addComponent(jComboBox1, 0, 199, Short.MAX_VALUE)))
                            .addGroup(lblltemsLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtBal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                    .addGroup(lblltemsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        lblltemsLayout.setVerticalGroup(
            lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblltemsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItems, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(lblltemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(lblltems, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 370, 390));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 120, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           model.setRowCount(0);

           lblItems.setText("");
           txtSub.setText("");
           txtPay.setText("");
           txtBal.setText("");
           txtCode.requestFocus();
           lblSubtoal.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeKeyReleased

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String itemCode = txtCode.getText();

            try {
                pst = con.prepareStatement("Select * from product where itemcode=?");
                pst.setString(1, itemCode);
                rs = pst.executeQuery();

                if (rs.next() == true) {
                    String productname = rs.getString("pname");
                    String price = rs.getString("price");

                    txtpname.setText(productname.trim());
                    txtPrice.setText(price.trim());
                } else {
                    JOptionPane.showMessageDialog(this, "Itemcode not Found");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_txtCodeKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int price = Integer.parseInt(txtPrice.getText());
        int qty = Integer.parseInt(txtQty.getText());
        
        int tot = price * qty;
        
        
        model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            txtCode.getText(),
            txtpname.getText(),
            txtQty.getText(),
            txtPrice.getText(),
            tot

        });

        int sum = 0;
        int items = jTable1.getRowCount();
        for (int i = 0; i < jTable1.getRowCount(); i++) 
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());

        }

//        txtSub.setText(Integer.toString(sum));
          txtSub.setText(Integer.toString(sum));
          lblSubtoal.setText(Integer.toString(sum));
          lblItems.setText(Integer.toString(items));


//          q.setText(Integer.toString(sum)); 

        txtCode.setText("");
        txtpname.setText("");
        txtQty.setText("");
        txtPrice.setText("");
        txtCode.requestFocus();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void txtPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtPayKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int subtot = Integer.parseInt(txtSub.getText());
         int pay = Integer.parseInt(txtPay.getText());
        
         int tot = pay - subtot ;
        
         txtBal.setText(String.valueOf(tot));  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblItemsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblItemsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblItemsAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblSubtoal;
    private javax.swing.JPanel lblltems;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCode1;
    private javax.swing.JTextField txtCode10;
    private javax.swing.JTextField txtCode11;
    private javax.swing.JTextField txtCode12;
    private javax.swing.JTextField txtCode13;
    private javax.swing.JTextField txtCode14;
    private javax.swing.JTextField txtCode15;
    private javax.swing.JTextField txtCode2;
    private javax.swing.JTextField txtCode3;
    private javax.swing.JTextField txtCode4;
    private javax.swing.JTextField txtCode5;
    private javax.swing.JTextField txtCode6;
    private javax.swing.JTextField txtCode7;
    private javax.swing.JTextField txtCode8;
    private javax.swing.JTextField txtCode9;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty10;
    private javax.swing.JTextField txtQty11;
    private javax.swing.JTextField txtQty12;
    private javax.swing.JTextField txtQty13;
    private javax.swing.JTextField txtQty14;
    private javax.swing.JTextField txtQty15;
    private javax.swing.JTextField txtQty16;
    private javax.swing.JTextField txtQty17;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtQty4;
    private javax.swing.JTextField txtQty5;
    private javax.swing.JTextField txtQty6;
    private javax.swing.JTextField txtQty7;
    private javax.swing.JTextField txtQty9;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtpname;
    // End of variables declaration//GEN-END:variables
}
